import 'package:dartz/dartz.dart';

import '../../core/error/failures.dart';
import '../entities/daily_script.dart';

/// Repository interface for script operations.
abstract class ScriptRepository {
  /// Get all scripts for a user.
  Future<Either<Failure, List<DailyScript>>> getScripts(String userId);

  /// Get script for a specific day.
  Future<Either<Failure, DailyScript?>> getScriptForDay(
    String userId,
    int dayNumber,
  );

  /// Generate personalized scripts based on user profile.
  /// If generation fails, fallback scripts are used.
  Future<Either<Failure, List<DailyScript>>> generateScripts({
    required String userId,
    required String goal,
    required String niche,
    required String fear,
    required String experience,
  });

  /// Save scripts generated by OpenAI.
  Future<Either<Failure, void>> saveGeneratedScripts({
    required String userId,
    required List<Map<String, dynamic>> scripts,
  });

  /// Load fallback (generic) scripts.
  Future<Either<Failure, List<DailyScript>>> loadFallbackScripts(String userId);

  /// Check if scripts are cached locally.
  Future<bool> hasLocalScripts(String userId);

  /// Clear cached scripts.
  Future<void> clearCache();
}
